### ISSUE TITLE
Test Performance stagnates after 10 epochs of Supervised Initialization

### ISSUE THREAD

**Issue by tomburgert** [psellcam/LaplaceNet#1]
Hello! 

I tried to run the following command:
`python main.py --dataset cifar100 --model wrn-28-8 --num-labeled 10000 --alpha 0.5 --lr 0.03 --labeled-batch-size 50 --aug-num 3 --label-split 12 --progress True` and when the 10 epochs of the supervised training have finished, there is no further improvement of the model when it enters the semi-supervised mode. The Top1 score remains at 0.63. I have some assumption that this bug regards to line 60 in main.py (which should contain one indent less) but I guess you will know better, what could cause this unexpected behavior.

Best,
Tom

**Comment by psellcam** [comment]
Yes Tom , it is indeed a bug in line 60.  Thanks for pointing it out, will correct now

**Comment by psellcam** [comment]
This change has now been made, please let me know if you still encounter the same error as before.

**Comment by tomburgert** [comment]
works perfectly now, thanks!

**Comment by psellcam** [comment]
Great I will close this issue
