### ISSUE TITLE
minor minor request about matplotlib

### ISSUE THREAD

**Issue by Ryoo72** [psellcam/LaplaceNet#2]
Matplotlib is additionally required to run prepare_cifar10.sh

It would be nice if 'pip install matplotlib' is added to the list.

- conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
- conda install -c pytorch faiss-gpu
- conda install -c anaconda scipy
- conda install -c conda-forge tqdm
- pip install torchnet
- pip install matplotlib

**Comment by psellcam** [comment]
Thank you for the comment, will add it now.
